runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  .env

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:px+1y0Y5FjDWv8u+sLre/swR5J8hhI57jk5APvI68Fg=
  STORAGE_DIR: /tmp
